# Exported from Render on 2024-11-17T01:17:44Z
services:
- type: web
  name: TDSDHT11.BLYNK-SERVER
  runtime: python
  repo: https://github.com/ThemeHackers/TDSDHT11.BLYNK-SERVER
  plan: free
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: . .venv/bin/activate && flask shell  && exec gunicorn -w 4 -k gthread
    --threads 2 --timeout 500 -b 0.0.0.0:5000 app:app
  previews:
    generation: automatic
version: "1"
